# Netlify config for SPA/PWA (Whylee v6007)
[build]
  publish = "."

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"

# Let the SPA handle routes (/#/home etc.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
