# ─────────────────────────────────────────────────────────
# Netlify config for Whylee (PWA)
# Includes: Functions bundling, CSP, SW caching, and secure headers
# ─────────────────────────────────────────────────────────

[build]
  publish = "."
  command = "" # Static PWA (no build step)

# ─────────────────────────────────────────────────────────
# Functions
# ─────────────────────────────────────────────────────────
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin", "stripe"]
  included_files = ["netlify/functions/_shared/**"]

# ─────────────────────────────────────────────────────────
# Environment (safe defaults)
# ─────────────────────────────────────────────────────────
# These variables are managed securely in the Netlify dashboard.
# DO NOT commit secret values to repo.
[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "true"

# ─────────────────────────────────────────────────────────
# Redirects
# ─────────────────────────────────────────────────────────
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[[redirects]]
  from = "/.well-known/*"
  to   = "/.well-known/:splat"
  status = 200

# ─────────────────────────────────────────────────────────
# Caching & Headers
# ─────────────────────────────────────────────────────────
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/scripts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/media/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# CORS for Netlify Functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# ─────────────────────────────────────────────────────────
# Security + Content Security Policy
# ─────────────────────────────────────────────────────────
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      base-uri 'self';
      frame-ancestors 'self';

      img-src 'self' data: blob:;
      media-src 'self' data:;
      font-src 'self' data:;
      object-src 'none';
      manifest-src 'self';
      worker-src 'self';
      style-src 'self' 'unsafe-inline';

      # JS: Firebase CDN + GTM (optional)
      script-src 'self' https://www.gstatic.com https://www.googletagmanager.com;

      # Connect: Allow all Firebase/Google endpoints required by Auth, Firestore, Storage
      connect-src
        'self'
        https://www.gstatic.com
        https://firestore.googleapis.com
        https://www.googleapis.com
        https://firebaseinstallations.googleapis.com
        https://identitytoolkit.googleapis.com
        https://securetoken.googleapis.com
        https://storage.googleapis.com
        https://www.google-analytics.com
        https://api.stripe.com;

      # Stripe for checkout
      frame-src 'self' https://js.stripe.com;
    """
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), interest-cohort=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
