[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      base-uri 'self';
      frame-ancestors 'self';

      img-src
        'self'
        data:
        blob:
        https://lh3.googleusercontent.com
        https://firebasestorage.googleapis.com;

      media-src 'self' data:;
      font-src 'self' data:;
      object-src 'none';
      manifest-src 'self';
      worker-src 'self';

      style-src 'self' 'unsafe-inline';

      # JS may only load from self + Firebase loader + GTM + Stripe
      script-src
        'self'
        https://www.gstatic.com
        https://www.googletagmanager.com
        https://www.google-analytics.com
        https://js.stripe.com;

      # Network/XHR/WebSocket endpoints used by Firebase/GA/Stripe
      connect-src
        'self'
        https://www.gstatic.com
        https://firestore.googleapis.com
        https://www.googleapis.com
        https://firebaseinstallations.googleapis.com
        https://identitytoolkit.googleapis.com
        https://securetoken.googleapis.com
        https://firebasestorage.googleapis.com
        https://www.google-analytics.com
        https://js.stripe.com
        https://api.stripe.com;

      # Allow Stripe checkout frames and (optionally) Google auth popups
      frame-src
        'self'
        https://js.stripe.com
        https://accounts.google.com;
    """
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), interest-cohort=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
