[build]
  publish = "."
  # (Optional) build command if you add tooling later:
  # command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# --- Caching for heavy/static assets ---
[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Manifest served with correct type
[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

# Basic security hardening (adjust as needed)
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"

# --- Scheduled Functions (autonomous daily questions) ---
[[functions]]
  schedule = "@daily"
  function = "generateDailyQuestions"

# NOTE:
# - SPA routing is handled by the `_redirects` file:
#       /*  /index.html  200
# - Set env vars in Netlify UI: FIREBASE_PROJECT_ID, FIREBASE_CLIENT_EMAIL, FIREBASE_PRIVATE_KEY, STRIPE_SECRET_KEY
