# Netlify config for Brain ⚡ Bolt — SPA + functions + headers

[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

# --- Pretty paths for HTML pages ---
[[redirects]]
  from = "/pro"
  to   = "/pro.html"
  status = 200

[[redirects]]
  from = "/about"
  to   = "/about.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to   = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to   = "/terms.html"
  status = 200

[[redirects]]
  from = "/contact"
  to   = "/contact.html"
  status = 200

[[redirects]]
  from = "/signin"
  to   = "/signin.html"
  status = 200

# --- Stripe checkout endpoint shortcut ---
[[redirects]]
  from = "/pro-checkout"
  to   = "/.netlify/functions/create-checkout-session"
  status = 200
  force = true

# --- SPA fallback ---
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# --- Explicit 404 page ---
[[redirects]]
  from = "/404.html"
  to   = "/404.html"
  status = 404

# --- Security headers ---
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# --- Cache rules ---
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/.netlify/functions/stripe-webhook"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Cache-Control = "no-cache"
