# Netlify config for Thynkr — SPA + functions + headers

[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

# Ensure functions aren't caught by SPA fallback
[[redirects]]
  from = "/.netlify/functions/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force = true

# Optional pretty path for Stripe Checkout session creation
[[redirects]]
  from = "/pro-checkout"
  to   = "/.netlify/functions/create-checkout-session"
  status = 200
  force = true

# Pass-through real files
[[redirects]]
  from = "/:file.:ext"
  to   = "/:file.:ext"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# 404 (optional for crawlers)
[[redirects]]
  from = "/404.html"
  to   = "/404.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Keep core app assets fresh (cache-busted via ?v=)
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "no-cache"

# Posters/icons: allow caching
[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"
