# Netlify config for Brain ⚡ Bolt — SPA + headers

[build]
  publish = "."
  command = ""

# Pass through real files
[[redirects]]
  from = "/:file.:ext"
  to   = "/:file.:ext"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Explicit 404
[[redirects]]
  from = "/404.html"
  to   = "/404.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Keep core app assets fresh
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "no-cache"
