# Netlify config for Brain ⚡ Bolt — clean SPA with pass-through for real files

[build]
  publish = "."
  command = ""

# 1) Let real files (with extensions) pass through unchanged
[[redirects]]
  from = "/:file.:ext"
  to   = "/:file.:ext"
  status = 200

# 2) SPA fallback for routes WITHOUT a file extension
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Optional: explicit 404 (served directly if requested)
[[redirects]]
  from = "/404.html"
  to   = "/404.html"
  status = 404

# --- Security headers ---
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# --- Keep core app assets fresh ---
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "no-cache"
