# ────────────────────────────────
# Whylee — Netlify Configuration
# v7006 (Autonomous Build)
# ────────────────────────────────

[build]
  publish = "."
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  command = "npm run start"
  port = 8888

# Environment variables are set in the Netlify UI:
# FIREBASE_PROJECT_ID, FIREBASE_CLIENT_EMAIL, FIREBASE_PRIVATE_KEY
# STRIPE_SECRET_KEY, STRIPE_PRICE_ID, LEADERBOARD_COLLECTION, LEADERBOARD_LIMIT

# ────────────────────────────────
# Redirects
# ────────────────────────────────
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ────────────────────────────────
# Scheduled (CRON) Functions
# ────────────────────────────────
# Run the daily question generator once a day at 05:00 UTC.
[[scheduled.functions]]
  name = "generateDailyQuestions"
  cron = "0 5 * * *"

# ────────────────────────────────
# Headers
# ────────────────────────────────
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# ────────────────────────────────
# PWA Cache Policy
# ────────────────────────────────
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# ────────────────────────────────
# Function Timeouts (optional tuning)
# ────────────────────────────────
[functions]
  node_bundler = "esbuild"
  included_files = ["media/questions/daily.csv"]
  timeout = 30
  memory = 256

# ────────────────────────────────
# END
# ────────────────────────────────
