# Netlify config for Brain ⚡ Bolt — SPA + functions + headers

[build]
  publish = "."
  command = ""
  functions = "netlify/functions"   # tell Netlify where your functions live

# Pretty path for Stripe Checkout session creation (optional)
[[redirects]]
  from = "/pro-checkout"
  to   = "/.netlify/functions/create-checkout-session"
  status = 200
  force = true

# Pass through real files
[[redirects]]
  from = "/:file.:ext"
  to   = "/:file.:ext"
  status = 200

# SPA fallback (this is fine; functions are resolved before redirects)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Explicit 404
[[redirects]]
  from = "/404.html"
  to   = "/404.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Keep core app assets fresh
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "no-cache"

# Optional: don't cache the webhook endpoint (harmless either way)
[[headers]]
  for = "/.netlify/functions/stripe-webhook"
  [headers.values]
    Cache-Control = "no-cache"

# Optional: manifest no-cache
[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Cache-Control = "no-cache"
