name: Deploy Firebase (Hosting + Functions)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Functions deps
        working-directory: functions
        run: npm ci

      - name: Set Functions Env (Gen2)
        # Optional: only if you prefer CLI over console env vars
        if: ${{ vars.USE_CLI_ENV == '1' }}
        run: |
          firebase functions:secrets:set STRIPE_SECRET --data="${{ secrets.STRIPE_SECRET }}"
          firebase functions:secrets:set STRIPE_WEBHOOK_SECRET --data="${{ secrets.STRIPE_WEBHOOK_SECRET }}"
          firebase functions:secrets:set PLAY_PACKAGE_NAME --data="${{ secrets.PLAY_PACKAGE_NAME }}"
          firebase functions:secrets:set GOOGLE_PLAY_SERVICE_ACCOUNT --data='${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}'

      - name: Deploy Hosting + Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only hosting,functions
